### PR TITLE
credit where credit's due!

### PR DESCRIPTION
**Pull request by ryan-allen**
thanks for gemming up and open sourcing my library

### CODE REVIEW

**Comment by dgoodlad** [comment]
@ryan-allen the `authors` array has special meaning to Rubygems, giving access to e.g. push new gems. I have no backing for this position, but would you be okay with a note/thanks in the README for your early contribution to the work?

**Comment by davidlee** [comment]
👍 I'm definitely in agreement FWIW. There are some expats in the current list of `authors` who should be removed, and some historic contributors missing who deserve to be credited (Ryan's contributions appear to predate the Github history) 

```
➜  double_entry git:(master) λ git log --format='%aN' | sort -u
Anthony Sellitti
Don Cote
Eaden
Eaden McKee
Envato
Giancarlo Salamanca
Jacob Bednarz
Jiexin Huang
Mark Turnley
Martin Spickermann
Mary-Anne Cosgrove
Orien Madgwick
Samuel Cochran
Sean Stavropoulos
Stephanie Staub
Trung Lê
```

**Comment by notahat** [comment]
@davidlee Yeah, the early Github history will be in the Market codebase, but may not even be credited correctly in there, coz I think the early code was in Subversion.

@ryan-allen While we're here, who else should get a mention? Clinton? JB?

**Comment by ryan-allen** [comment]
Clinton for sure, and Vahid!

**Comment by salamagd** [comment]
Closed in favour of #131

**Pull request closed without merging**
