### PR TITLE
pass constant as string to avoid issues with spring

### PR DESCRIPTION
**Pull request by doncote**
#115

### CODE REVIEW

**Comment by orien** [comment]
Thanks @doncote. Could we maintain backwards compatibility by supporting both a class and a string?

**Comment by doncote** [comment]
Definitely.  I'll add that and let you know when I push.

**Comment by cinqi** [comment]
Is there any progress on this matter? Apparently this is waiting for the compatibility issue to be fixed?

**Comment by jeffnappi** [comment]
Another viable option here is to simply use this in development:

```ruby
# Reload class references for DoubleEntry
ActiveSupport::Reloader.to_prepare do
  load 'config/initializers/double_entry.rb'
end
```

In our case we do this at the bottom of our `development.rb` environment config.

**Comment by swrobel** [comment]
@jeffnappi sometimes seeing the following error - have you encountered it?

`vendor/bundle/gems/double_entry-1.0.0/lib/double_entry/account.rb:50:in '<<': DoubleEntry::DuplicateAccount (DoubleEntry::DuplicateAccount)`

**Comment by swrobel** [comment]
@doncote sadly your fix doesn't seem to resolve this for me, I believe because the initializer still converts the string to a constant when it runs, and thus that version of the class is cached 🤔

**Comment by jeffnappi** [comment]
@swrobel I haven't had the pleasure of seeing that happen (yet). Another option is to stop using Spring and use [Bootsnap](https://github.com/Shopify/bootsnap).

**Comment by swrobel** [comment]
For reference, I got rid of spring but was still seeing this in rails console after running `reload!` and this solution finally worked for me:

1) Add the following to the bottom of `development.rb` ([suggested above](https://github.com/envato/double_entry/pull/117#issuecomment-295944797)):
```ruby
# Reload class references for DoubleEntry
ActiveSupport::Reloader.to_prepare do
  load 'config/initializers/double_entry.rb'
end
```

2) Add the following to `config/initializers/double_entry.rb` above your account definitions (tweak of [this suggestion](https://github.com/envato/double_entry/issues/115#issuecomment-229362706)):
```ruby
DoubleEntry.configure do |config|
  # Fix for when this is run multiple times, ex: dev mode reloading
  config.accounts = nil

  # the rest of your config goes below
```

**Comment by orien** [comment]
Closing in favour of removing `active_record_scope_identifier` altogether. See #153.

**Pull request closed without merging**
