### PR TITLE
feat: Gem update ruby 3

### PR DESCRIPTION
**Pull request by achhetr**

### CODE REVIEW

**Comment by viraptor** [comment]
This also addresses ruby 2.7's

> warning: Capturing the given block using Proc.new is deprecated; use `&block` instead

**Review by scottyp-env — APPROVED** [review]
Thanks for this!

**Review by ricobl — APPROVED** [review]
Thanks @achhetr!

**Comment by achhetr** [comment]
@ricobl @scottyp-env 
Can we merge this PR in??

**Comment by ricobl** [comment]
It's merged @achhetr! But it might take a while for us to cut a new release. I hope that works for you.

**Pull request merged**
