### PR TITLE
Fix #133, specify which version of ActiveRecord::Migration to inherit from

### LINKED ISSUE #133: Rails 5 issue:  Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:
```
StandardError: An error has occurred, this and all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateDoubleEntryTables < ActiveRecord::Migration[4.2]
/APP_NAME/db/migrate/20171128034808_create_double_entry_tables.rb:1:in `<top (required)>'
/APP_NAME/config/initializers/task.rb:7:in `execute'
```

As the error message recommends, I was able to fix this for Rails 5 by specifying the correct version in the migration (currently it just outputs `class CreateDoubleEntryTables < ActiveRecord::Migration`).  

This seems like an easy PR to bring in, and would prevent people from shooting themselves in the foot when adding this gem for the first time.

### PR DESCRIPTION
**Pull request by KelseyDH**
Fixes #133, which is that in Rails 5 this gem breaks if we inherit from ActiveRecord::Migration without specifying a version.

(I chose 4.2 assuming that was the latest version of ActiveRecord this database migration upgrade was targeted for.)

### CODE REVIEW

**Comment by KelseyDH** [comment]
I added conditional code to ensure graceful fallback for older rails projects

**Comment by KelseyDH** [comment]
My old code was incorrect I realize.  I updated the migration script to something that looks more elegant based on how Devise dealt with this migration, making the migration look more elegant to the end user.

**Comment by orien** [comment]
Looks great.

The CI build is failing though.
```
1) DoubleEntry::Generators::InstallGenerator generates the expected migrations
     Failure/Error: if Rails.version > '5'
     
     NoMethodError:
       undefined method `version' for Rails:Module
     # ./lib/generators/double_entry/install/install_generator.rb:21:in `migration_version'
     # ./lib/generators/double_entry/install/install_generator.rb:17:in `copy_migrations'
```

I think because this gem doesn't depending on Rails, rather ActiveRecord.

Try using `ActiveRecord.version.version`.

**Comment by KelseyDH** [comment]
@orien  Thanks for pointing out the fix!  Tests are passing now.

**Comment by orien** [comment]
Thanks @KelseyDH. Do you mind adding an entry in the [`CHANGELOG.md`](https://github.com/envato/double_entry/blob/master/CHANGELOG.md#unreleased).

**Comment by KelseyDH** [comment]
done!

**Comment by orien** [comment]
👏 Thanks for this contribution @KelseyDH!

**Pull request merged**
